name: <%= themeName %>
type: theme
description: '<%= themeName %> Theme'
package: <%= themeName %>
base theme: false
core: 8.x
core_version_requirement: ^8 || ^9
libraries:
  - <%= themeName %>/globals

regions:
  header: Header
  messages: Messages
  content: Content
  footer: Footer

# component-libraries:
#   storybook:
#     paths:
#       - ../../../../storybook/twig
